language: csharp
dist: trusty
sudo: required
addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main'
      key_url: 'https://apt-mo.trafficmanager.net/keys/microsoft.asc'
    packages:
    - dotnet-dev-1.0.1
script:
  - dotnet restore
  - dotnet build
  - cd NuKeeper.Tests
  - dotnet test

 